
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: cyclops
      POSTGRES_PASSWORD: <docker-swarm-secret>
      POSTGRES_DB: cyclopsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cyclops-net

  redis:
    image: redis:7
    networks:
      - cyclops-net

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - cyclops-net
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      - cyclops-net

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: <docker-swarm-secret>
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - cyclops-net

networks:
  cyclops-net:
    driver: overlay

volumes:
  pgdata:
  minio_data:
